name: Mr_Popup
main: top.ascserver.mr_popup.Timers
version: "1.3.5"
api: ["1.0.0"]
load: POSTWORLD
author: Mr_sky
description: 一款良心底部
commands:
  popup:
    description: Mr_Popup主命令
#commands: []
#permissions: []